// SPDX-License-Identifier: MIT

package renderers

import (
	"fmt"
	"sort"
	"strings"

	"github.com/davidarce/devrune/internal/model"
)

// CatalogBeginMarker is the opening delimiter for the DevRune-managed block
// in root catalog files (AGENTS.md, CLAUDE.md).
const CatalogBeginMarker = "# >>> devrune managed — do not edit"

// CatalogEndMarker is the closing delimiter for the DevRune-managed block
// in root catalog files.
const CatalogEndMarker = "# <<< devrune managed"

// RenderRootCatalog produces the agent-agnostic AGENTS.md content string.
// It emits the auto-generated header, a Workflows section with each workflow's
// injected registry content, and per-MCP agent-instruction sections.
//
// Skills, decision rules, invocation controls, and project rules are NOT
// rendered: agents discover skills/rules through their own runtime mechanisms,
// and the disambiguation tables duplicate signal that lives in skill bodies
// and advisor logic.
//
// The returned string does not include the managed block markers — the caller
// is responsible for wrapping via WriteManagedBlock.
//
// Parameters:
//   - workflows: installed workflow manifests
//   - mcpInstructions: map of MCP name → agent instructions text
//   - registryContents: map of workflow name → registry content to inject
func RenderRootCatalog(
	workflows []model.WorkflowManifest,
	mcpInstructions map[string]string,
	registryContents map[string]string,
) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Agent Catalog\n\n")
	sb.WriteString("This file is auto-generated by DevRune. Do not edit manually.\n\n")

	// Workflows section — contains highest-priority instructions (e.g. SDD Evaluation Gate).
	if len(workflows) > 0 {
		sb.WriteString("## Workflows\n\n")
		for _, wf := range workflows {
			_, _ = fmt.Fprintf(&sb, "### %s\n\n", wf.Metadata.EffectiveDisplayName())
			if len(wf.Components.Commands) > 0 {
				sb.WriteString("| Command | Action |\n")
				sb.WriteString("|---------|--------|\n")
				for _, cmd := range wf.Components.Commands {
					cmdStr := "/" + cmd.Name
					if cmd.Argument != "" {
						cmdStr += " " + cmd.Argument
					}
					_, _ = fmt.Fprintf(&sb, "| `%s` | %s |\n", cmdStr, cmd.Action)
				}
				sb.WriteString("\n")
			}

			// Inject workflow registry content if available.
			if content, ok := registryContents[wf.Metadata.Name]; ok && content != "" {
				sb.WriteString(content)
				if !strings.HasSuffix(content, "\n") {
					sb.WriteString("\n")
				}
				sb.WriteString("\n")
			}
		}
	}

	// Append MCP agent instructions sections (sorted for deterministic output).
	// Skip MCPs without instructions. If instructions already start with a ##
	// header, don't add a duplicate header.
	mcpNames := make([]string, 0, len(mcpInstructions))
	for name := range mcpInstructions {
		mcpNames = append(mcpNames, name)
	}
	sort.Strings(mcpNames)
	for _, name := range mcpNames {
		instructions := strings.TrimSpace(mcpInstructions[name])
		if instructions == "" {
			continue
		}
		if !strings.HasPrefix(instructions, "## ") {
			_, _ = fmt.Fprintf(&sb, "## %s\n\n", capitalizeFirst(name))
		}
		sb.WriteString(instructions)
		if !strings.HasSuffix(instructions, "\n") {
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	return sb.String(), nil
}
