// SPDX-License-Identifier: MIT

package renderers

import (
	"fmt"
	"sort"
	"strings"

	"github.com/davidarce/devrune/internal/model"
)

// CatalogBeginMarker is the opening delimiter for the DevRune-managed block
// in root catalog files (AGENTS.md, CLAUDE.md).
const CatalogBeginMarker = "# >>> devrune managed — do not edit"

// CatalogEndMarker is the closing delimiter for the DevRune-managed block
// in root catalog files.
const CatalogEndMarker = "# <<< devrune managed"

// RenderRootCatalog produces the agent-agnostic AGENTS.md content string.
// It merges skills, rules, and workflows into a single unified catalog.
// The returned string does not include the managed block markers — the caller
// is responsible for wrapping via WriteManagedBlock.
//
// Parameters:
//   - skills: installed skill content items (from all agents, deduplicated by caller)
//   - rules: installed rule content items
//   - workflows: installed workflow manifests
//   - mcpInstructions: map of MCP name → agent instructions text
//   - registryContents: map of workflow name → registry content to inject
func RenderRootCatalog(
	skills []model.ContentItem,
	rules []model.ContentItem,
	workflows []model.WorkflowManifest,
	mcpInstructions map[string]string,
	registryContents map[string]string,
) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Agent Catalog\n\n")
	sb.WriteString("This file is auto-generated by DevRune. Do not edit manually.\n\n")

	// Workflows section FIRST — contains highest-priority instructions (SDD Evaluation Gate).
	if len(workflows) > 0 {
		sb.WriteString("## Workflows\n\n")
		for _, wf := range workflows {
			_, _ = fmt.Fprintf(&sb, "### %s\n\n", wf.Metadata.Name)
			if wf.Metadata.Description != "" {
				sb.WriteString(wf.Metadata.Description + "\n\n")
			}
			if len(wf.Components.Commands) > 0 {
				sb.WriteString("| Command | Action |\n")
				sb.WriteString("|---------|--------|\n")
				for _, cmd := range wf.Components.Commands {
					cmdStr := "/" + cmd.Name
					if cmd.Argument != "" {
						cmdStr += " " + cmd.Argument
					}
					_, _ = fmt.Fprintf(&sb, "| `%s` | %s |\n", cmdStr, cmd.Action)
				}
				sb.WriteString("\n")
			}

			// Inject workflow registry content if available.
			if content, ok := registryContents[wf.Metadata.Name]; ok && content != "" {
				sb.WriteString(content)
				if !strings.HasSuffix(content, "\n") {
					sb.WriteString("\n")
				}
				sb.WriteString("\n")
			}
		}
	}

	// Skills table.
	if len(skills) > 0 {
		sb.WriteString("## Skills\n\n")
		sb.WriteString("| Skill | Invocation | Use When |\n")
		sb.WriteString("|-------|------------|----------|\n")
		for _, s := range skills {
			_, _ = fmt.Fprintf(&sb, "| `%s` | `/%s` | %s |\n", s.Name, s.Name, s.Description)
		}
		sb.WriteString("\n")
	}

	// Collect decision rules from all workflows.
	var allDecisionRules []model.DecisionRule
	for _, wf := range workflows {
		allDecisionRules = append(allDecisionRules, wf.Components.DecisionRules...)
	}
	if len(allDecisionRules) > 0 {
		sb.WriteString("## Decision Rules\n\n")
		sb.WriteString("When multiple skills could apply, prefer the FIRST match in this priority table.\n\n")
		sb.WriteString("| Scenario | Resolution |\n")
		sb.WriteString("|----------|------------|\n")
		for _, dr := range allDecisionRules {
			_, _ = fmt.Fprintf(&sb, "| %s | %s |\n", dr.Scenario, dr.Resolution)
		}
		sb.WriteString("\n")
	}

	// Collect invocation controls from all workflows.
	var allInvocationControls []model.InvocationControl
	for _, wf := range workflows {
		allInvocationControls = append(allInvocationControls, wf.Components.InvocationControls...)
	}
	if len(allInvocationControls) > 0 {
		sb.WriteString("## Invocation Controls\n\n")
		for _, ic := range allInvocationControls {
			_, _ = fmt.Fprintf(&sb, "- %s - %s\n", ic.Skills, ic.Description)
		}
		sb.WriteString("\n")
	}

	// Project Rules table.
	if len(rules) > 0 {
		sb.WriteString("## Project Rules\n\n")
		sb.WriteString("Technology-specific rules loaded by advisers based on scope matching.\n\n")
		sb.WriteString("| Rule | Scope | Technology | Applies To | Description |\n")
		sb.WriteString("|------|-------|------------|------------|-------------|\n")
		for _, rule := range rules {
			scope := ""
			technology := ""
			appliesTo := ""
			description := rule.Description
			if rule.RuleMeta != nil {
				scope = rule.RuleMeta.Scope
				technology = rule.RuleMeta.Technology
				appliesTo = rule.RuleMeta.AppliesTo
				if rule.RuleMeta.Description != "" {
					description = rule.RuleMeta.Description
				}
			}
			displayName := rule.Name
			if rule.RuleMeta != nil && rule.RuleMeta.DisplayName != "" {
				displayName = rule.RuleMeta.DisplayName
			}
			_, _ = fmt.Fprintf(&sb, "| `%s` | %s | %s | %s | %s |\n",
				displayName, scope, technology, appliesTo, description)
		}
		sb.WriteString("\n")
	}

	// Append MCP agent instructions sections (sorted for deterministic output).
	// Skip MCPs without instructions. If instructions already start with a ##
	// header, don't add a duplicate header.
	mcpNames := make([]string, 0, len(mcpInstructions))
	for name := range mcpInstructions {
		mcpNames = append(mcpNames, name)
	}
	sort.Strings(mcpNames)
	for _, name := range mcpNames {
		instructions := strings.TrimSpace(mcpInstructions[name])
		if instructions == "" {
			continue
		}
		if !strings.HasPrefix(instructions, "## ") {
			_, _ = fmt.Fprintf(&sb, "## %s\n\n", capitalizeFirst(name))
		}
		sb.WriteString(instructions)
		if !strings.HasSuffix(instructions, "\n") {
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	return sb.String(), nil
}
